name: 'Bug Report'
description: Create a new ticket for a bug
title: '[BUG] <title>'
labels: ['bug']
body:
  - type: dropdown
    attributes:
      label: 'Environment'
      description: What is the impacted environment?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false
  - type:
    attributes:
      label:
      description:
      placeholder:
  - type: textarea
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: macOS Big Sur
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Version
      description: What version of our software are you running?
      multiple: false
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description:
        The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](link/to/coc)
          required: true
  - type: markdown
    attributes:
      value: 'Thanks for completing our form!'
  - type: checkboxes
    attributes:
      label: Checklists
      description: Please select that all applies
      options:
        - label: My code follows the style guidelines of this project
        - label: I have performed a self-review of my own code
        - label: I have created reusable components wherever possible.
          required: false
