name: 'Bug Report'
description: Create a new ticket for a bug
title: '[BUG] <title>'
labels: ['bug']
body:
  - type: dropdown
    id: SampleId
    attributes:
      label: 'Operating system'
      description: List all OS(s) impacted.
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false
  - type: dropdown
    attributes:
      label: 'Browser'
      description: List all browser(s) impacted.
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Brave
        - Microsoft Edge
        - Opera
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: 'Steps to Reproduce'
      description: Please list all the steps to reproduce
      placeholder: step 1
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 'Expected Behavior'
      description: Describe what you expected to happen
      placeholder: start typing
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 'Actual Behavior'
      description: Describe what actually happened
      placeholder: start typing
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 'Additional Details'
      description: Provide any additional details or context related to the issue
      placeholder: start typing
    validations:
      required: true
