name: '💡 Feature Request'
description: Create a new ticket for a new feature request
title: '💡 [REQUEST] - <title>'
labels: ['question']
body:
  - type: input
    id: start_date
    attributes:
      label: 'Start Date'
      description: Start of development
      placeholder: 'month/day/year'
    validations:
      required: false
